name: Compile sing-box Geosite and Geoip

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  compile-geosite-srs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Necessary Tools
        run: |
          sudo apt install -y curl wget git

      - name: Install sing-box
        run: |
          sudo curl -fsSL https://sing-box.app/gpg.key -o /etc/apt/keyrings/sagernet.asc
          sudo chmod a+r /etc/apt/keyrings/sagernet.asc
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/sagernet.asc] https://deb.sagernet.org/ * *" | \
          sudo tee /etc/apt/sources.list.d/sagernet.list > /dev/null
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades sing-box=1.8.14

      - name: Prepare Folders
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          mkdir -p geosite geoip adguard
          sudo chown -R $USER:$USER geosite geoip adguard
          sudo chmod -R 755 geosite geoip adguard

      - name: Download db
        run: |
          wget -O geosite.db https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.db
          wget -O geoip.db https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.db

      - name: Export telegram Json
        run: |
          sing-box geosite -f geosite.db export telegram
          sing-box geoip -f geoip.db export telegram

      - name: Compile telegram Source
        run: |
          sing-box rule-set compile --output geosite/geosite-telegram.srs geosite-telegram.json
          sing-box rule-set compile --output geoip/geoip-telegram.srs geoip-telegram.json

      - name: Export google-scholar Json
        run: |
          sing-box geosite -f geosite.db export google-scholar

      - name: Compile google-scholar Source
        run: |
          sing-box rule-set compile --output geosite/geosite-google-scholar.srs geosite-google-scholar.json

      - name: Export google Json
        run: |
          sing-box geosite -f geosite.db export google
          sing-box geoip -f geoip.db export google

      - name: Compile google Source
        run: |
          sing-box rule-set compile --output geosite/geosite-google.srs geosite-google.json
          sing-box rule-set compile --output geoip/geoip-google.srs geoip-google.json

      - name: Export win-update Json
        run: |
          sing-box geosite -f geosite.db export win-update

      - name: Compile win-update Source
        run: |
          sing-box rule-set compile --output geosite/geosite-win-update.srs geosite-win-update.json

      - name: Export netflix Json
        run: |
          sing-box geosite -f geosite.db export netflix
          sing-box geoip -f geoip.db export netflix

      - name: Compile netflix Source
        run: |
          sing-box rule-set compile --output geosite/geosite-netflix.srs geosite-netflix.json
          sing-box rule-set compile --output geoip/geoip-netflix.srs geoip-netflix.json

      - name: Update sing-box
        run: |
          sudo apt-get install -y sing-box-beta

      - name: Download Adguard Filters
        run: |
          curl -fsSL https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt > adguard.txt

      - name: Compile Adguard Source
        run: |
          sing-box rule-set convert --type adguard --output adguard/adguard.srs adguard.txt

      - name: Push Files
        run: |
          echo "Force updating repository with local content..."
          git checkout -b Release
          git add geoip geosite adguard
          git commit -m "Update srs files"
          git push --force origin Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create tag
        id: create_tag
        run: |
          TAG_NAME=$(date -u +"%Y%m%d%H%M%S")
          if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
            echo "Tag $TAG_NAME already exists, deleting it from remote."
            git push --delete origin "$TAG_NAME"
            while git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; do
              echo "Waiting for tag $TAG_NAME to be deleted..."
              sleep 5
            done
          fi
          git tag $TAG_NAME
          git push --force origin $TAG_NAME
          echo "::set-output name=TAG_NAME::$TAG_NAME"

      - name: Create release
        id: create_release
        run: |
          TAG_NAME=${{ steps.create_tag.outputs.TAG_NAME }}
          RELEASE_ID=$(gh release view "$TAG_NAME" --json id --jq '.id' || echo "null")
          if [ "$RELEASE_ID" != "null" ]; then
            echo "Release $TAG_NAME already exists, deleting it."
            gh release delete "$TAG_NAME" --yes
          fi
          gh release create "$TAG_NAME" --title "$TAG_NAME" --notes "Auto-generated release for $TAG_NAME" geosite/*.srs geoip/*.srs adguard/*.srs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
